codecov:
  bot: "azd-codecov"
  require_ci_to_pass: true
comment:
  behavior: default
  layout: " diff, flags, files"
coverage:
  precision: 2
  range:
    - 60.0
    - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: true
github_checks:
  annotations: true
flag_management:
  individual_flags:
    - name: unittests
      statuses:
        - type: project
          target: 50%
          threshold: 10%
        - type: patch
          target: 50%
          threshold: 10%
    - name: integration-ubuntu-latest
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: integration-mac-latest
      statuses:
        - type: project
          target: auto
          threshold: 1%
